[editor]
mouse = true
cursorline = true
# cursorcolumn = true
line-number = "relative"
# idle-timeout = 1000
true-color = true
color-modes = true
# auto-info = false
# gutters = ["diagnostics"]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
# insert = "block"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.statusline]                                                                    
left = ["mode", "spinner", "file-name"]                                                           
center = []                                                                            
right = ["diagnostics", "selections", "position", "file-type"]     

[keys.normal]
"A-a" = { "r" = ":sh cargo run", "t" = ":sh cargo test" }
