theme = "helix_dark"

[editor]
mouse = true
cursorline = true
true-color = true
color-modes = true
auto-info = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "file-type"]

[keys.normal]
";" = { "r" = ":sh cargo run", "t" = ":sh cargo test", "c" = ":sh cargo clippy --fix", "o" = [
  "add_newline_below",
  "add_newline_below",
  "move_line_down",
  "move_line_down",
  "insert_mode",
], "O" = [
  "add_newline_above",
  "add_newline_above",
  "add_newline_above",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "insert_mode",
]}
