inherits = "default"

[palette]
white = "#ffffff"
lilac = "#dbbfef"
lavender = "#a4a0e8"
comet = "#5a5977"
bossanova = "#2e0b40"  # cursorline
midnight = "#25003e"
revolver = "#281733"

silver = "#cccccc"
sirocco = "#697C81"
mint = "#9ff28f"
almond = "#eccdba"
chamois = "#E8DCA0"
honey = "#efba5d"

apricot = "#bdc3c7"
lightning = "#ffcd1c"
delta = "#6F44F0"
